[package]
name = "gvnos/statemachine"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
UILabs = "pepeeltoro41/ui-labs@2.3.8"
ReactFlow = "outofbears/react-flow@0.1.6"
iris = "sirmallard/iris@2.3.1"
signal = "sleitnick/signal@1.4.1"
Promise = "evaera/promise@4.0.0"
comm="sleitnick/comm@0.3.1"
zentag = "gavinostler/zentag@0.2.1"